# Generated by Django 3.2 on 2021-05-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_item', models.CharField(max_length=200)),
                ('ds_prioridade', models.CharField(max_length=200)),
            ],
        ),
    ]
