# Generated by Django 3.2 on 2021-05-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_listpriority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpriority',
            name='ds_item',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listpriority',
            name='ds_prioridade',
            field=models.TextField(max_length=200),
        ),
    ]
