# Generated by Django 3.2 on 2021-05-16 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_alter_listpriority_ds_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListPriority',
        ),
    ]
