# Generated by Django 3.2 on 2021-05-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_delete_listpriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ds_prio',
            field=models.TextField(default=''),
        ),
    ]
