# Generated by Django 3.2 on 2021-05-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_item_ds_prio'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
